/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Country = IDL.Record({
  'name' : IDL.Text,
  'currency' : IDL.Text,
  'capital' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCountries' : IDL.Func([], [IDL.Vec(Country)], ['query']),
  'searchCountries' : IDL.Func([IDL.Text], [IDL.Vec(Country)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Country = IDL.Record({
    'name' : IDL.Text,
    'currency' : IDL.Text,
    'capital' : IDL.Text,
  });
  
  return IDL.Service({
    'getCountries' : IDL.Func([], [IDL.Vec(Country)], ['query']),
    'searchCountries' : IDL.Func([IDL.Text], [IDL.Vec(Country)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };